spring.application.name=worldForge

spring.datasource.url=jdbc:postgresql://localhost:5432/worldForge_db
spring.datasource.username=postgres
spring.datasource.password=1937

# Estratégia de atualização do Banco (Muito importante no início!)
spring.jpa.hibernate.ddl-auto=update

# Mostrar as queries SQL no console (ajuda a aprender o que o Spring faz por baixo dos panos)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true